version: '3'

services:
    python:
        image: bloodyburger/lido:latest
        container_name: lido
        volumes:
            - ./src:/lido
        env_file:
            - ./config.env    
        ports:
            - 8000:8000