# Generated by Django 4.1.7 on 2023-04-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_delete_reportsconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_filters",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "secondary_filters",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "account_filters",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "category_filters",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "subcategory_filters",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "show_primary",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO")],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "show_secondary",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO")],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "show_account",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO")],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "show_category",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO")],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "show_subcategory",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "YES"), ("NO", "NO")],
                        default=None,
                        max_length=3,
                    ),
                ),
                ("base_token", models.TextField(blank=True, default=None)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reports",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Report Config",
                "db_table": "reports_config",
            },
        ),
    ]
