# Generated by Django 4.1.7 on 2023-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_reportsconfig_source_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsconfig",
            name="show_as_dollar",
            field=models.CharField(
                choices=[("currency", "Yes"), ("fixedPoint", "No")],
                default="fixedPoint",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
