# Generated by Django 4.1.7 on 2023-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_reportsconfig_show_as_dollar"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsconfig",
            name="value_as_cumulative",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
            preserve_default=False,
        ),
    ]
