# Generated by Django 4.1.7 on 2023-04-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_reportsconfig_value_as_cumulative"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsconfig",
            name="show_token",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No")], default="NO", max_length=3
            ),
            preserve_default=False,
        ),
    ]
