# Generated by Django 4.1.7 on 2023-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_reportsconfig_filter_known_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsconfig",
            name="fold_primary",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
