# Generated by Django 4.1.7 on 2023-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0013_reportsconfig_expand_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsconfig",
            name="drilldown_cols",
            field=models.TextField(
                default=(
                    "PERIOD",
                    "PRIMARY_LABEL",
                    "SECONDARY_LABEL",
                    "ACCOUNT",
                    "BASE_TOKEN_ADDRESS",
                    "VALUE_BASE_TOKEN",
                    "TOKEN_PRICE",
                    "VALUE_ETH",
                    "VALUE_USD",
                    "LAG_PRICE_USD",
                    "LAG_PRICE_ETH",
                )
            ),
            preserve_default=False,
        ),
    ]
