# Generated by Django 4.1.7 on 2023-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0014_reportsconfig_drilldown_cols"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "File Uploads",
            },
        ),
    ]
