# Generated by Django 4.1.7 on 2023-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_uploads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploads",
            name="filename",
        ),
        migrations.AddField(
            model_name="uploads",
            name="document",
            field=models.FileField(default=1, upload_to="documents/"),
            preserve_default=False,
        ),
    ]
